### ISSUE TITLE
React list form: Getting an 'TypeError: Cannot read property 'indexOf' of undefined' when trying to load some list forms

### ISSUE THREAD

**Issue by JenniferUXWeb** [pnp/sp-dev-fx-webparts#1566]
Authors:
@sharepointknight 
@Harshagracy 
@DanyWyss 

Issue:

I've recently noticed that some of my react list forms are no longer loading and I'm getting the following error  '**TypeError: Cannot read property 'indexOf' of undefined' when trying to load some list forms**'. 
![image](https://user-images.githubusercontent.com/68618534/97449237-5ed06000-1929-11eb-8faa-94da3b5670b2.png)

This error began to occur after I deployed the most recent update of the SPFX web part. It's really strange because it only seems to be affecting a handful of my forms and I can't quite pin-point what is triggering the error. The majority of my forms are working as expected.

Any help would be much appreciated.

Steps to reproduce the error:

- Deploy latest React List Form release
- Open an existing SharePoint Modern page with React List form web part
- Delete web part and re-add to the page
- Choose list from options
- Error message appears in web part (only affects some lists).

**Comment by bcameron1231** [comment]
hi, are you able to provide the definitions for your list which would help us reproduce the issue?

**Comment by sharepointknight** [comment]
I believe I have fixed this in the other fixes I am working on. I believe it is related to different handling of Lookup fields by SharePoint. I'll make sure this fix gets committed shortly.

**Comment by bcameron1231** [comment]
Thanks @sharepointknight . I assigned this to you so it doesn't get lost 👍

**Comment by JenniferUXWeb** [comment]
> I believe I have fixed this in the other fixes I am working on. I believe it is related to different handling of Lookup fields by SharePoint. I'll make sure this fix gets committed shortly.

Once again, thank you so soo much @sharepointknight your hard work and efforts are very much appreciated!!!

**Comment by benkenawell** [comment]
Hi @sharepointknight , is this related to the Lookup columns no longer returning a Choices field in the sharepoint api call?  I've had a similar issue in a webpart for my day job and I'd be happy to help with this issue if they're similar.

**Comment by elilongwell** [comment]
It seems this issue is still active in the most recent build for me. Like others, it's only happening to random lists and some work fine, but I can't seem to find any particular reasons for it.

**Comment by elilongwell** [comment]
Actually, I was just able to troubleshoot this by testing it on a copy of the list and removing columns one by one until it worked. It turns out that having a "Person or Group" column set to "Show Field: Name (with presence)" is what's breaking it. Once I set all "Person or Group" columns to name only, it began working as intended. Is this intentional?

@sharepointknight
@Harshagracy
@DanyWyss
